/**
 * Callout extensions (RMF C.75).
 *
 * Callouts are short (≤25 char) snippets that appear below text ads, e.g.
 * "Free shipping", "24/7 support". In the Google Ads API they are modeled
 * as `asset` resources with `asset.callout_asset`, then linked at the
 * customer (account), campaign, or ad-group level via `customer_asset`,
 * `campaign_asset`, or `ad_group_asset` respectively.
 */

import { getCachedCustomer } from "./client";
import {
  createAssetWithLinks,
  isAutomaticallyCreatedAssetSource,
  normalizeAssetSource,
  type AssetLinkMutationResult,
  type AssetLinkTarget,
} from "./asset-links";
import type { AuthContext } from "./types";

// ─── Reads ──────────────────────────────────────────────────────────

export type CalloutAsset = {
  assetId: string;
  resourceName: string;
  text: string;
  source: string | null;
  autoGenerated: boolean;
  linkedAtAccount: boolean;
  accountLinkResourceName: string | null;
};

export type CreateCalloutAssetParams = {
  text: string;
  targets?: AssetLinkTarget[];
};

type CalloutAssetRow = {
  asset?: {
    id?: string | number;
    resource_name?: string;
    source?: string | number;
    callout_asset?: { callout_text?: string };
  };
};
type CustomerAssetLinkRow = {
  customer_asset?: {
    asset?: string;
    resource_name?: string;
  };
};

/** List all callout assets on the account, with whether each is linked at the customer level. */
export async function listCalloutAssets(auth: AuthContext): Promise<CalloutAsset[]> {
  const customer = getCachedCustomer(auth);

  const assetsResult = await customer.query(`
    SELECT
      asset.id,
      asset.resource_name,
      asset.source,
      asset.callout_asset.callout_text
    FROM asset
    WHERE asset.type = CALLOUT
    LIMIT 500
  `);

  const linksResult = await customer.query(`
    SELECT
      customer_asset.asset,
      customer_asset.resource_name,
      customer_asset.field_type,
      customer_asset.status
    FROM customer_asset
    WHERE customer_asset.field_type = CALLOUT
      AND customer_asset.status != REMOVED
  `);

  const linkByAsset = new Map<string, string>();
  for (const row of linksResult as CustomerAssetLinkRow[]) {
    const assetResource = row.customer_asset?.asset;
    const linkResource = row.customer_asset?.resource_name;
    if (assetResource && linkResource) linkByAsset.set(assetResource, linkResource);
  }

  return (assetsResult as CalloutAssetRow[]).map((row) => {
    const assetResource = row.asset?.resource_name ?? "";
    const linkResource = linkByAsset.get(assetResource) ?? null;
    const source = normalizeAssetSource(row.asset?.source);
    return {
      assetId: String(row.asset?.id ?? ""),
      resourceName: assetResource,
      text: row.asset?.callout_asset?.callout_text ?? "",
      source,
      autoGenerated: isAutomaticallyCreatedAssetSource(source),
      linkedAtAccount: linkResource !== null,
      accountLinkResourceName: linkResource,
    };
  });
}

// ─── Writes ─────────────────────────────────────────────────────────

/**
 * Create a callout asset. With `targets`, also link it at customer/campaign/
 * ad-group levels in the same atomic mutate. Without `targets`, the asset is
 * created but not linked — use `linkAsset` later.
 */
export async function createCalloutAsset(
  auth: AuthContext,
  params: CreateCalloutAssetParams,
): Promise<AssetLinkMutationResult> {
  const text = params.text.trim();
  const action = "create_callout_asset";

  if (!text) {
    return {
      success: false,
      action,
      entityId: "",
      beforeValue: "",
      afterValue: "",
      error: "Callout text cannot be empty",
      fieldType: "CALLOUT",
      assetId: "",
      assetResourceName: "",
    };
  }
  if (text.length > 25) {
    return {
      success: false,
      action,
      entityId: "",
      beforeValue: "",
      afterValue: text,
      error: "Callout text must be 25 characters or fewer",
      fieldType: "CALLOUT",
      assetId: "",
      assetResourceName: "",
    };
  }

  return createAssetWithLinks(auth, {
    fieldType: "CALLOUT",
    assetResource: {
      callout_asset: { callout_text: text },
    },
    targets: params.targets ?? [],
    action,
    afterValue: text,
    label: text,
  });
}
