import { getCachedCustomer } from "./client";
import {
  createAssetWithLinks,
  isAutomaticallyCreatedAssetSource,
  normalizeAssetSource,
  type AssetLinkMutationResult,
  type AssetLinkTarget,
} from "./asset-links";
import { isValidFinalUrl } from "./helpers";
import type { AuthContext } from "./types";

export type SitelinkAsset = {
  assetId: string;
  resourceName: string;
  linkText: string;
  finalUrls: string[];
  description1: string;
  description2: string;
  source: string | null;
  autoGenerated: boolean;
  linkedAtAccount: boolean;
  accountLinkResourceName: string | null;
};

export type SitelinkAssetParams = {
  linkText: string;
  finalUrl: string;
  description1?: string;
  description2?: string;
};

export type CreateSitelinkAssetParams = SitelinkAssetParams & {
  targets?: AssetLinkTarget[];
};

type SitelinkAssetRow = {
  asset?: {
    id?: string | number;
    resource_name?: string;
    final_urls?: string[];
    source?: string | number;
    sitelink_asset?: {
      link_text?: string;
      description1?: string;
      description2?: string;
    };
  };
};
type CustomerAssetLinkRow = {
  customer_asset?: {
    asset?: string;
    resource_name?: string;
  };
};

function normalizeSitelinkInput(
  params: SitelinkAssetParams,
): { linkText?: string; finalUrl?: string; description1?: string; description2?: string; error?: string } {
  const linkText = params.linkText.trim();
  const finalUrl = params.finalUrl.trim();
  const description1 = params.description1?.trim() ?? "";
  const description2 = params.description2?.trim() ?? "";

  if (!linkText) return { error: "Sitelink text cannot be empty" };
  if (linkText.length > 25) return { error: "Sitelink text must be 25 characters or fewer" };
  if (!isValidFinalUrl(finalUrl)) return { error: "Sitelink finalUrl must be a valid http(s) URL" };
  if ((description1 && !description2) || (!description1 && description2)) {
    return { error: "Sitelink descriptions must be provided as a pair: description1 and description2" };
  }
  if (description1.length > 35) return { error: "Sitelink description1 must be 35 characters or fewer" };
  if (description2.length > 35) return { error: "Sitelink description2 must be 35 characters or fewer" };

  return { linkText, finalUrl, description1, description2 };
}

function sitelinkAssetResource(input: {
  linkText: string;
  finalUrl: string;
  description1?: string;
  description2?: string;
}): Record<string, unknown> {
  return {
    final_urls: [input.finalUrl],
    sitelink_asset: {
      link_text: input.linkText,
      ...(input.description1 && input.description2
        ? { description1: input.description1, description2: input.description2 }
        : {}),
    },
  };
}

export async function listSitelinkAssets(auth: AuthContext): Promise<SitelinkAsset[]> {
  const customer = getCachedCustomer(auth);

  const assetsResult = await customer.query(`
    SELECT
      asset.id,
      asset.resource_name,
      asset.final_urls,
      asset.source,
      asset.sitelink_asset.link_text,
      asset.sitelink_asset.description1,
      asset.sitelink_asset.description2
    FROM asset
    WHERE asset.type = SITELINK
    LIMIT 500
  `);

  const linksResult = await customer.query(`
    SELECT
      customer_asset.asset,
      customer_asset.resource_name,
      customer_asset.field_type,
      customer_asset.status
    FROM customer_asset
    WHERE customer_asset.field_type = SITELINK
      AND customer_asset.status != REMOVED
  `);

  const linkByAsset = new Map<string, string>();
  for (const row of linksResult as CustomerAssetLinkRow[]) {
    const assetResource = row.customer_asset?.asset;
    const linkResource = row.customer_asset?.resource_name;
    if (assetResource && linkResource) linkByAsset.set(assetResource, linkResource);
  }

  return (assetsResult as SitelinkAssetRow[]).map((row) => {
    const assetResource = row.asset?.resource_name ?? "";
    const accountLinkResourceName = linkByAsset.get(assetResource) ?? null;
    const source = normalizeAssetSource(row.asset?.source);
    return {
      assetId: String(row.asset?.id ?? ""),
      resourceName: assetResource,
      linkText: row.asset?.sitelink_asset?.link_text ?? "",
      finalUrls: row.asset?.final_urls ?? [],
      description1: row.asset?.sitelink_asset?.description1 ?? "",
      description2: row.asset?.sitelink_asset?.description2 ?? "",
      source,
      autoGenerated: isAutomaticallyCreatedAssetSource(source),
      linkedAtAccount: accountLinkResourceName !== null,
      accountLinkResourceName,
    };
  });
}

/**
 * Create a sitelink asset. With `targets`, also link it at customer/campaign/
 * ad-group levels in the same atomic mutate. Without `targets`, the asset is
 * created but not linked — use `linkAsset` later.
 */
export async function createSitelinkAsset(
  auth: AuthContext,
  params: CreateSitelinkAssetParams,
): Promise<AssetLinkMutationResult> {
  const action = "create_sitelink_asset";
  const normalized = normalizeSitelinkInput(params);
  if (normalized.error) {
    return {
      success: false,
      action,
      entityId: "",
      beforeValue: "",
      afterValue: JSON.stringify({ linkText: params.linkText, finalUrl: params.finalUrl }),
      error: normalized.error,
      fieldType: "SITELINK",
      assetId: "",
      assetResourceName: "",
    };
  }

  const input = normalized as { linkText: string; finalUrl: string; description1?: string; description2?: string };
  return createAssetWithLinks(auth, {
    fieldType: "SITELINK",
    assetResource: sitelinkAssetResource(input),
    targets: params.targets ?? [],
    action,
    afterValue: `${input.linkText} -> ${input.finalUrl}`,
    label: input.linkText,
  });
}
