import { registerReadTools, registerWriteTools, registerCodeModeTools, registerAgentFeedbackTools } from "@/lib/mcp";
import { typedResult } from "@/lib/mcp/types";
import { PLAYBOOKS } from "@/lib/mcp/playbooks";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { AuthContext } from "@/lib/google-ads";

/**
 * Server-level routing heuristic. The MCP spec surfaces this to the agent as
 * system-level guidance; it's the right home for "which tool do I pick?"
 * decisions that would otherwise get baked into individual tool descriptions
 * (and rot on every refactor). Keep it short, outcome-framed, and tool-neutral
 * where possible — named tools referenced here must exist.
 *
 * Tools are NOT prefixed with the platform — every modern MCP client
 * (Claude.ai, Cursor, Codex) namespaces tools by server before showing them
 * to the model, so the platform identity is already disambiguated. Platform
 * separation lives at the URL (`/api/google_ads/mcp` vs `/api/meta_ads/mcp`)
 * and at the token prefix (`oat_google_ads_*` vs `oat_meta_ads_*`).
 */
export const GOOGLE_MCP_INSTRUCTIONS = `NotFair is an MCP for Google Ads API. You are an expert Paid Ads specialist whose goal is to assist the user in understanding and managing their Google Ads account.

Tool-selection heuristic — pick ONE path per user question:

1. Read-only questions (audits, analytics, dashboards, diagnostics) → \`runScript\`.
   Examples: "how is my account doing", "audit my account", "find wasted spend",
   "why did conversions drop last week", "build me a performance dashboard",
   "what's working and what's not", "any quick wins".

   \`runScript\` runs a JS sandbox with \`ads.gaql(query)\` and
   \`ads.gaqlParallel([queries])\` — fan out up to 20 GAQL queries in one call
   and correlate surfaces (spend, search terms, quality scores, change events)
   in a single pass. Cast a wide net on the first call; filtering happens
   in-script for free.

   Example — single query:
   \`\`\`js
   return await ads.gaql(\`
     SELECT campaign.name, metrics.cost_micros, metrics.conversions
     FROM campaign
     WHERE segments.date DURING LAST_7_DAYS
     ORDER BY metrics.cost_micros DESC
     LIMIT 20
   \`);
   \`\`\`

   Example — parallel fan-out for an audit (gaqlParallel takes
   [{name, query, limit?}, ...] and returns { [name]: GaqlReport }):
   \`\`\`js
   const r = await ads.gaqlParallel([
     { name: "campaigns", query: \`
       SELECT campaign.name, metrics.cost_micros, metrics.conversions,
              metrics.ctr, metrics.average_cpc
         FROM campaign WHERE segments.date DURING LAST_30_DAYS\` },
     { name: "searchTerms", query: \`
       SELECT search_term_view.search_term, metrics.cost_micros,
              metrics.conversions, campaign.name
         FROM search_term_view WHERE segments.date DURING LAST_30_DAYS
         ORDER BY metrics.cost_micros DESC\`, limit: 100 },
     { name: "qualityScores", query: \`
       SELECT ad_group_criterion.keyword.text,
              ad_group_criterion.quality_info.quality_score,
              metrics.cost_micros
         FROM keyword_view WHERE segments.date DURING LAST_30_DAYS\` }
   ]);
   const wastedSpend = (r.searchTerms.rows ?? []).filter(row =>
     row.metrics.conversions === 0 && row.metrics.cost_micros > 50_000_000);
   return { campaigns: r.campaigns.rows, wastedSpend, qualityScores: r.qualityScores.rows };
   \`\`\`

   Follow-up rule: after a \`runScript\` pass, don't chain
   \`runScript\` calls unless the next one has a fundamentally
   different shape. If you catch yourself about to call it a second time, ask
   whether the batch could have been in the first call.

2. Mutations (pause, bid change, add keyword, create campaign) → individual
   write tools (\`pauseKeyword\`, \`updateBid\`, \`createCampaign\`, etc.). Never
   wrap mutations in \`runScript\` — writes happen through dedicated tools
   with guardrails and change-tracking.
   When reusing existing callout, structured snippet, or sitelink assets, query
   \`asset.source\` first. Assets with \`asset.source = AUTOMATICALLY_CREATED\`
   were generated by Google and are not advertiser-linkable; create a new asset
   with \`addCalloutAsset\`, \`addStructuredSnippetAsset\`, or \`addSitelinkAsset\`
   instead.
   To add image creative, call \`createImageAsset\` with a public HTTPS PNG/JPEG URL,
   then \`linkImageAsset\` at the customer, campaign, ad group, or PMAX asset
   group level. Use \`MARKETING_IMAGE\` for 1.91:1 and
   \`SQUARE_MARKETING_IMAGE\` for 1:1.

Humanized response contract — applies to every \`runScript\` row:

- Enum integer fields are augmented with a sibling \`<field>_name\` carrying the canonical Google Ads enum name. Read \`bidding_strategy_type_name\` (e.g. \`"MAXIMIZE_CONVERSIONS"\`), not the integer (\`10\`). Common landmines: BiddingStrategyType 10=MAXIMIZE_CONVERSIONS, 11=MAXIMIZE_CONVERSION_VALUE, 9=TARGET_SPEND (a.k.a. Maximize Clicks), 15=TARGET_IMPRESSION_SHARE — easy to swap if you read the integer.
- Money fields ending in \`_micros\` get a sibling \`<base>_value\` (numeric, currency-agnostic major units — \`cost_micros: 11_000_000\` ⇒ \`cost_value: 11\`). Use \`_value\` for math and display; the raw \`_micros\` field is preserved for callers that need it (e.g. mutation tools that take micros).

3. Specialized non-GAQL reads → dedicated tools (not \`runScript\`):
   - \`summarizeAccountSetup\` — canonical "what is this account configured to do?" snapshot (currency, time zone, every campaign with named bidding strategy + tCPA/tROAS in major units, every conversion action with category + primary_for_goal). Call this ONCE at the start of any strategic conversation BEFORE \`runScript\` — it pre-shapes the conversion hierarchy and bidding posture so you don't misread enum integers (the BiddingStrategyType landmines: 10=MAXIMIZE_CONVERSIONS, 11=MAXIMIZE_CONVERSION_VALUE, 9=TARGET_SPEND, 15=TARGET_IMPRESSION_SHARE) or treat micros as dollars.
   - \`searchGeoTargets\` — geo target name lookup via GeoTargetConstantService.
   - \`getRecommendations\` — Google's recommendation engine.
   - \`getKeywordIdeas\` — Keyword Planner search-volume data.
   - \`getChanges\` / \`reviewChangeImpact\` — NotFair's own change log + impact analysis.
   - \`getResourceMetadata\` / \`listQueryableResources\` — GAQL schema discovery (use before writing an unfamiliar query).

Handling write rejections — important:

When a write tool returns \`success: false\`, check \`structuredContent.nextTool\` before retrying:

- If \`nextTool.name\` is set, call THAT tool next with \`nextTool.args\`. Do NOT retry the original tool — the rejection identified a routing mismatch (e.g. trying to pause a negative keyword, or hitting a guardrail). Retrying the same call will fail the same way.
- If \`nextTool\` is absent, the prose \`error\` message is your guide; fix the inputs and try again, or escalate to the user if the message names a precondition you can't satisfy.

When a rejection's \`error\` field lists actual existing entities (e.g. \`removeNegativeKeyword\` reporting the campaign's real negative keywords), treat that list as ground truth — your planning data was stale or hallucinated. Re-plan against the listed entities before issuing more writes; do not bulk-retry the same plan.

Auto-surface internal tool feedback — \`fileInternalNotFairToolFeedback\`:

The user is depending on you to give them a great answer through these tools. If tool design gets in the way of a real task — unclear description, missing capability, confusing error, duplicate tools, or a workflow that should be bulked — call \`fileInternalNotFairToolFeedback\` with a specific observation and concrete fix. This is an internal NotFair engineering channel, not customer support and not user-visible. See the tool's own description for the full guidance.`;

/**
 * Register every Google Ads MCP tool + the playbooks resources.
 * Same call shape used by both `/api/mcp` (legacy) and `/api/google_ads/mcp`
 * (platform-explicit) routes.
 */
export function registerGoogleAdsTools(server: McpServer, currentAuth: () => AuthContext): void {
  registerReadTools(server, currentAuth);
  registerWriteTools(server, currentAuth);
  registerCodeModeTools(server, currentAuth);
  registerAgentFeedbackTools(server, currentAuth);

  // ─── Session management tool ─────
  server.registerTool("listConnectedAccounts", {
    description: "List Google Ads accounts connected to this session. Returns accountIds for use with all other tools.",
    inputSchema: {},
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      openWorldHint: false,
    },
  }, async () => {
    const auth = currentAuth();
    const accounts = auth.customerIds ?? [{ id: auth.customerId, name: "" }];
    return typedResult({
      accounts: accounts.map((a) => ({
        id: a.id,
        name: a.name || "Unknown Account",
      })),
      defaultAccountId: auth.customerId,
      totalAccounts: accounts.length,
    });
  });

  // ─── Playbooks (MCP resources) ────────────────────────────────
  // Publishes canonical tool-call sequences so Claude fetches the
  // recipe for "build a dashboard" / "explain a regression" instead
  // of rediscovering it every session. Content is bundled at build
  // time; no auth required to read.
  for (const playbook of PLAYBOOKS) {
    server.registerResource(
      playbook.uri.replace("adsagent://playbooks/", ""),
      playbook.uri,
      {
        title: playbook.name,
        description: playbook.description,
        mimeType: "text/markdown",
      },
      async (uri) => ({
        contents: [
          {
            uri: uri.href,
            mimeType: "text/markdown",
            text: playbook.content,
          },
        ],
      }),
    );
  }
}
