import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockCustomerFactory, mockMutateResources, mockQuery } = vi.hoisted(() => ({
  mockCustomerFactory: vi.fn(),
  mockMutateResources: vi.fn(),
  mockQuery: vi.fn(),
}));

vi.mock("@/lib/env", () => ({
  getRequiredEnv: vi.fn((name: string) => `${name.toLowerCase()}-value`),
  getEnv: vi.fn((name: string) => `${name.toLowerCase()}-value`),
}));

vi.mock("google-ads-api", () => ({
  GoogleAdsApi: class {
    Customer = mockCustomerFactory;
  },
}));

import { linkSitelinkAsset, listSitelinkAssets } from "@/lib/google-ads";

const auth = { refreshToken: "refresh-token", customerId: "130-126-5570" };

describe("sitelinks", () => {
  beforeEach(() => {
    mockCustomerFactory.mockReset();
    mockMutateResources.mockReset();
    mockQuery.mockReset();
    mockCustomerFactory.mockReturnValue({
      mutateResources: mockMutateResources,
      query: mockQuery,
    });
  });

  it("returns sitelink assets annotated with asset source", async () => {
    mockQuery
      .mockResolvedValueOnce([
        {
          asset: {
            id: "5",
            resource_name: "customers/1301265570/assets/5",
            final_urls: ["https://example.com/pricing"],
            source: "ADVERTISER",
            sitelink_asset: {
              link_text: "Pricing",
              description1: "See current plans",
              description2: "Compare options",
            },
          },
        },
        {
          asset: {
            id: "6",
            resource_name: "customers/1301265570/assets/6",
            final_urls: ["https://example.com/contact"],
            source: "AUTOMATICALLY_CREATED",
            sitelink_asset: {
              link_text: "Contact",
            },
          },
        },
      ])
      .mockResolvedValueOnce([
        {
          customer_asset: {
            asset: "customers/1301265570/assets/5",
            resource_name: "customers/1301265570/customerAssets/5~13",
          },
        },
      ]);

    const result = await listSitelinkAssets(auth);

    expect(result).toHaveLength(2);
    expect(result[0]).toMatchObject({
      assetId: "5",
      linkText: "Pricing",
      source: "ADVERTISER",
      autoGenerated: false,
      linkedAtAccount: true,
    });
    expect(result[1]).toMatchObject({
      assetId: "6",
      linkText: "Contact",
      source: "AUTOMATICALLY_CREATED",
      autoGenerated: true,
      linkedAtAccount: false,
    });
  });

  it("rejects automatically-created sitelinks before linking", async () => {
    mockQuery.mockResolvedValueOnce([{ asset: { source: "AUTOMATICALLY_CREATED" } }]);

    const result = await linkSitelinkAsset(auth, {
      assetId: "999",
      target: { level: "campaign", campaignId: "123" },
    });

    expect(result).toMatchObject({
      success: false,
      action: "link_sitelink_asset",
      assetId: "999",
      assetResourceName: "customers/1301265570/assets/999",
    });
    expect(result.error).toMatch(/automatically created by Google/i);
    expect(mockMutateResources).not.toHaveBeenCalled();
  });
});
