import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockCustomerFactory, mockMutateResources, mockQuery } = vi.hoisted(() => ({
  mockCustomerFactory: vi.fn(),
  mockMutateResources: vi.fn(),
  mockQuery: vi.fn(),
}));

vi.mock("@/lib/env", () => ({
  getRequiredEnv: vi.fn((name: string) => `${name.toLowerCase()}-value`),
  getEnv: vi.fn((name: string) => `${name.toLowerCase()}-value`),
}));

vi.mock("google-ads-api", () => ({
  GoogleAdsApi: class {
    Customer = mockCustomerFactory;
  },
}));

import { createSitelinkAsset, linkAsset, listSitelinkAssets } from "@/lib/google-ads";

const auth = { refreshToken: "refresh-token", customerId: "130-126-5570" };

describe("sitelinks", () => {
  beforeEach(() => {
    mockCustomerFactory.mockReset();
    mockMutateResources.mockReset();
    mockQuery.mockReset();
    mockCustomerFactory.mockReturnValue({
      mutateResources: mockMutateResources,
      query: mockQuery,
    });
  });

  it("returns sitelink assets annotated with asset source", async () => {
    mockQuery
      .mockResolvedValueOnce([
        {
          asset: {
            id: "5",
            resource_name: "customers/1301265570/assets/5",
            final_urls: ["https://example.com/pricing"],
            source: "ADVERTISER",
            sitelink_asset: {
              link_text: "Pricing",
              description1: "See current plans",
              description2: "Compare options",
            },
          },
        },
        {
          asset: {
            id: "6",
            resource_name: "customers/1301265570/assets/6",
            final_urls: ["https://example.com/contact"],
            source: "AUTOMATICALLY_CREATED",
            sitelink_asset: {
              link_text: "Contact",
            },
          },
        },
      ])
      .mockResolvedValueOnce([
        {
          customer_asset: {
            asset: "customers/1301265570/assets/5",
            resource_name: "customers/1301265570/customerAssets/5~13",
          },
        },
      ]);

    const result = await listSitelinkAssets(auth);

    expect(result).toHaveLength(2);
    expect(result[0]).toMatchObject({
      assetId: "5",
      linkText: "Pricing",
      source: "ADVERTISER",
      autoGenerated: false,
      linkedAtAccount: true,
    });
    expect(result[1]).toMatchObject({
      assetId: "6",
      linkText: "Contact",
      source: "AUTOMATICALLY_CREATED",
      autoGenerated: true,
      linkedAtAccount: false,
    });
  });

  it("createSitelinkAsset (no targets) creates the asset only", async () => {
    mockMutateResources.mockResolvedValueOnce({
      mutate_operation_responses: [
        { asset_result: { resource_name: "customers/1301265570/assets/999" } },
      ],
    });
    const result = await createSitelinkAsset(auth, {
      linkText: "Pricing",
      finalUrl: "https://example.com/pricing",
    });
    expect(result.success).toBe(true);
    expect(result.action).toBe("create_sitelink_asset");
    expect(result.fieldType).toBe("SITELINK");
    expect(mockMutateResources.mock.calls[0][0]).toHaveLength(1);
  });

  it("rejects phone numbers in sitelink text before Google policy rejection", async () => {
    const result = await createSitelinkAsset(auth, {
      linkText: "Free Consultation",
      finalUrl: "https://example.com/free-consultation",
      description1: "On-site estimate fast",
      description2: "Call (818) 900-7479",
    });

    expect(result.success).toBe(false);
    expect(result.error).toContain("PHONE_NUMBER_IN_AD_TEXT");
    expect(mockMutateResources).not.toHaveBeenCalled();
  });

  it("createSitelinkAsset with campaign target produces atomic create+link", async () => {
    mockMutateResources.mockResolvedValueOnce({
      mutate_operation_responses: [
        { asset_result: { resource_name: "customers/1301265570/assets/999" } },
        { campaign_asset_result: { resource_name: "customers/1301265570/campaignAssets/100~999~13" } },
      ],
    });
    const result = await createSitelinkAsset(auth, {
      linkText: "Pricing",
      finalUrl: "https://example.com/pricing",
      description1: "See current plans",
      description2: "Compare every option",
      targets: [{ level: "campaign", campaignId: "100" }],
    });
    expect(result.success).toBe(true);
    expect(mockMutateResources.mock.calls[0][0][0].resource).toMatchObject({
      final_urls: ["https://example.com/pricing"],
      sitelink_asset: {
        link_text: "Pricing",
        description1: "See current plans",
        description2: "Compare every option",
      },
    });
    expect(mockMutateResources.mock.calls[0][0][1].resource).toMatchObject({
      campaign: "customers/1301265570/campaigns/100",
      field_type: 13,
    });
  });

  it("linkAsset rejects automatically-created sitelinks before linking", async () => {
    mockQuery.mockResolvedValueOnce([{ asset: { source: "AUTOMATICALLY_CREATED" } }]);

    const result = await linkAsset(auth, {
      assetId: "999",
      fieldType: "SITELINK",
      targets: [{ level: "campaign", campaignId: "123" }],
    });

    expect(result).toMatchObject({
      success: false,
      assetId: "999",
      assetResourceName: "customers/1301265570/assets/999",
      fieldType: "SITELINK",
    });
    expect(result.error).toMatch(/automatically created by Google/i);
    expect(mockMutateResources).not.toHaveBeenCalled();
  });
});
